#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NeptunLight.Droid.Resource", IsApplication=true)]

namespace NeptunLight.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::NeptunLight.Droid.Resource.String.library_name;
			global::Splat.Resource.String.library_name = global::NeptunLight.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int alignmentMode = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int columnCount = 2130771970;
			
			// aapt resource value: 0x7f010016
			public const int columnGap = 2130771990;
			
			// aapt resource value: 0x7f010006
			public const int columnOrderPreserved = 2130771974;
			
			// aapt resource value: 0x7f01001a
			public const int dayBackgroundColor = 2130771994;
			
			// aapt resource value: 0x7f010022
			public const int dayNameLength = 2130772002;
			
			// aapt resource value: 0x7f010026
			public const int eventCornerRadius = 2130772006;
			
			// aapt resource value: 0x7f010024
			public const int eventMarginVertical = 2130772004;
			
			// aapt resource value: 0x7f010020
			public const int eventPadding = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int eventTextColor = 2130771999;
			
			// aapt resource value: 0x7f010013
			public const int eventTextSize = 2130771987;
			
			// aapt resource value: 0x7f01000e
			public const int firstDayOfWeek = 2130771982;
			
			// aapt resource value: 0x7f010029
			public const int futureBackgroundColor = 2130772009;
			
			// aapt resource value: 0x7f01002b
			public const int futureWeekendBackgroundColor = 2130772011;
			
			// aapt resource value: 0x7f010021
			public const int headerColumnBackground = 2130772001;
			
			// aapt resource value: 0x7f010014
			public const int headerColumnPadding = 2130771988;
			
			// aapt resource value: 0x7f010017
			public const int headerColumnTextColor = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int headerRowBackgroundColor = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int headerRowPadding = 2130771989;
			
			// aapt resource value: 0x7f010030
			public const int horizontalFlingEnabled = 2130772016;
			
			// aapt resource value: 0x7f01000f
			public const int hourHeight = 2130771983;
			
			// aapt resource value: 0x7f01001b
			public const int hourSeparatorColor = 2130771995;
			
			// aapt resource value: 0x7f01001e
			public const int hourSeparatorHeight = 2130771998;
			
			// aapt resource value: 0x7f01000a
			public const int layout_column = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_columnSpan = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_columnWeight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_gravity = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int layout_row = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_rowSpan = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_rowWeight = 2130771977;
			
			// aapt resource value: 0x7f010011
			public const int maxHourHeight = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int minHourHeight = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int noOfVisibleDays = 2130771992;
			
			// aapt resource value: 0x7f01002e
			public const int nowLineColor = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int nowLineThickness = 2130772015;
			
			// aapt resource value: 0x7f010000
			public const int orientation = 2130771968;
			
			// aapt resource value: 0x7f010023
			public const int overlappingEventGap = 2130772003;
			
			// aapt resource value: 0x7f01002a
			public const int pastBackgroundColor = 2130772010;
			
			// aapt resource value: 0x7f01002c
			public const int pastWeekendBackgroundColor = 2130772012;
			
			// aapt resource value: 0x7f010001
			public const int rowCount = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int rowOrderPreserved = 2130771973;
			
			// aapt resource value: 0x7f010027
			public const int showDistinctPastFutureColor = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int showDistinctWeekendColor = 2130772008;
			
			// aapt resource value: 0x7f01002d
			public const int showNowLine = 2130772013;
			
			// aapt resource value: 0x7f010012
			public const int textSize = 2130771986;
			
			// aapt resource value: 0x7f01001c
			public const int todayBackgroundColor = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int todayHeaderTextColor = 2130771997;
			
			// aapt resource value: 0x7f010003
			public const int useDefaultMargins = 2130771971;
			
			// aapt resource value: 0x7f010031
			public const int verticalFlingEnabled = 2130772017;
			
			// aapt resource value: 0x7f010025
			public const int xScrollingSpeed = 2130772005;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int default_gap = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int message_title_box = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int InstituteSelector = 2131099691;
			
			// aapt resource value: 0x7f06002e
			public const int LoginButton = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int LoginField = 2131099692;
			
			// aapt resource value: 0x7f06003b
			public const int MessageList = 2131099707;
			
			// aapt resource value: 0x7f06002d
			public const int PasswordField = 2131099693;
			
			// aapt resource value: 0x7f06003f
			public const int PeriodList = 2131099711;
			
			// aapt resource value: 0x7f060002
			public const int alignBounds = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int alignMargins = 2131099651;
			
			// aapt resource value: 0x7f060044
			public const int averageTextView = 2131099716;
			
			// aapt resource value: 0x7f060004
			public const int bottom = 2131099652;
			
			// aapt resource value: 0x7f060032
			public const int calendarButton = 2131099698;
			
			// aapt resource value: 0x7f06003c
			public const int categoryTextView = 2131099708;
			
			// aapt resource value: 0x7f060005
			public const int center = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int center_horizontal = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int center_vertical = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int clip_horizontal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int clip_vertical = 2131099657;
			
			// aapt resource value: 0x7f060038
			public const int contentTextView = 2131099704;
			
			// aapt resource value: 0x7f060033
			public const int coursesButton = 2131099699;
			
			// aapt resource value: 0x7f060042
			public const int creditInfoTextView = 2131099714;
			
			// aapt resource value: 0x7f060045
			public const int cumulativeAverageTextView = 2131099717;
			
			// aapt resource value: 0x7f060025
			public const int dateTextView = 2131099685;
			
			// aapt resource value: 0x7f06000a
			public const int end = 2131099658;
			
			// aapt resource value: 0x7f06003e
			public const int endDateTextView = 2131099710;
			
			// aapt resource value: 0x7f06002f
			public const int errorText = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int examList = 2131099690;
			
			// aapt resource value: 0x7f060034
			public const int examsButton = 2131099700;
			
			// aapt resource value: 0x7f060021
			public const int expandableList = 2131099681;
			
			// aapt resource value: 0x7f06000b
			public const int fill = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int fill_horizontal = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int fill_vertical = 2131099661;
			
			// aapt resource value: 0x7f060030
			public const int fragmentHolder = 2131099696;
			
			// aapt resource value: 0x7f060012
			public const int friday = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int horizontal = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int left = 2131099662;
			
			// aapt resource value: 0x7f060019
			public const int length_long = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int length_short = 2131099674;
			
			// aapt resource value: 0x7f060039
			public const int letterBox = 2131099705;
			
			// aapt resource value: 0x7f06001d
			public const int line1 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int line2 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int line3 = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int listTitle = 2131099676;
			
			// aapt resource value: 0x7f060027
			public const int locationTextView = 2131099687;
			
			// aapt resource value: 0x7f060031
			public const int messagesButton = 2131099697;
			
			// aapt resource value: 0x7f060013
			public const int monday = 2131099667;
			
			// aapt resource value: 0x7f060020
			public const int pager = 2131099680;
			
			// aapt resource value: 0x7f060036
			public const int periodsButton = 2131099702;
			
			// aapt resource value: 0x7f060029
			public const int resultTextView = 2131099689;
			
			// aapt resource value: 0x7f06000f
			public const int right = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int saturday = 2131099668;
			
			// aapt resource value: 0x7f060046
			public const int semesterList = 2131099718;
			
			// aapt resource value: 0x7f060040
			public const int semesterNameTextView = 2131099712;
			
			// aapt resource value: 0x7f060035
			public const int semestersButton = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int senderTextView = 2131099703;
			
			// aapt resource value: 0x7f060010
			public const int start = 2131099664;
			
			// aapt resource value: 0x7f06003d
			public const int startDateTextView = 2131099709;
			
			// aapt resource value: 0x7f060041
			public const int statusTextView = 2131099713;
			
			// aapt resource value: 0x7f060023
			public const int subjectTextView = 2131099683;
			
			// aapt resource value: 0x7f060015
			public const int sunday = 2131099669;
			
			// aapt resource value: 0x7f060022
			public const int textView1 = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int textView2 = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int textView3 = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int textView5 = 2131099688;
			
			// aapt resource value: 0x7f060016
			public const int thursday = 2131099670;
			
			// aapt resource value: 0x7f06003a
			public const int titleTextView = 2131099706;
			
			// aapt resource value: 0x7f060011
			public const int top = 2131099665;
			
			// aapt resource value: 0x7f060043
			public const int totalCreditInfoTextView = 2131099715;
			
			// aapt resource value: 0x7f060017
			public const int tuesday = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int vertical = 2131099649;
			
			// aapt resource value: 0x7f060018
			public const int wednesday = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int weekView = 2131099675;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CalendarPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CoursesListGroup = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CoursesListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CoursesPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CoursesTab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ExamListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ExamsPage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ExamsTab = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LoginPage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MenuPage = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MessageDetailsPage = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MessageListItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MessagesPage = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PeriodsListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PeriodsPage = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SemestersListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SemestersPage = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GridLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public const int GridLayout_alignmentMode = 4;
			
			// aapt resource value: 2
			public const int GridLayout_columnCount = 2;
			
			// aapt resource value: 6
			public const int GridLayout_columnOrderPreserved = 6;
			
			// aapt resource value: 0
			public const int GridLayout_orientation = 0;
			
			// aapt resource value: 1
			public const int GridLayout_rowCount = 1;
			
			// aapt resource value: 5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 3
			public const int GridLayout_useDefaultMargins = 3;
			
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 10
			public const int GridLayout_Layout_layout_column = 10;
			
			// aapt resource value: 11
			public const int GridLayout_Layout_layout_columnSpan = 11;
			
			// aapt resource value: 12
			public const int GridLayout_Layout_layout_columnWeight = 12;
			
			// aapt resource value: 13
			public const int GridLayout_Layout_layout_gravity = 13;
			
			// aapt resource value: 7
			public const int GridLayout_Layout_layout_row = 7;
			
			// aapt resource value: 8
			public const int GridLayout_Layout_layout_rowSpan = 8;
			
			// aapt resource value: 9
			public const int GridLayout_Layout_layout_rowWeight = 9;
			
			public static int[] WeekView = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017};
			
			// aapt resource value: 8
			public const int WeekView_columnGap = 8;
			
			// aapt resource value: 12
			public const int WeekView_dayBackgroundColor = 12;
			
			// aapt resource value: 20
			public const int WeekView_dayNameLength = 20;
			
			// aapt resource value: 24
			public const int WeekView_eventCornerRadius = 24;
			
			// aapt resource value: 22
			public const int WeekView_eventMarginVertical = 22;
			
			// aapt resource value: 18
			public const int WeekView_eventPadding = 18;
			
			// aapt resource value: 17
			public const int WeekView_eventTextColor = 17;
			
			// aapt resource value: 5
			public const int WeekView_eventTextSize = 5;
			
			// aapt resource value: 0
			public const int WeekView_firstDayOfWeek = 0;
			
			// aapt resource value: 27
			public const int WeekView_futureBackgroundColor = 27;
			
			// aapt resource value: 29
			public const int WeekView_futureWeekendBackgroundColor = 29;
			
			// aapt resource value: 19
			public const int WeekView_headerColumnBackground = 19;
			
			// aapt resource value: 6
			public const int WeekView_headerColumnPadding = 6;
			
			// aapt resource value: 9
			public const int WeekView_headerColumnTextColor = 9;
			
			// aapt resource value: 11
			public const int WeekView_headerRowBackgroundColor = 11;
			
			// aapt resource value: 7
			public const int WeekView_headerRowPadding = 7;
			
			// aapt resource value: 34
			public const int WeekView_horizontalFlingEnabled = 34;
			
			// aapt resource value: 1
			public const int WeekView_hourHeight = 1;
			
			// aapt resource value: 13
			public const int WeekView_hourSeparatorColor = 13;
			
			// aapt resource value: 16
			public const int WeekView_hourSeparatorHeight = 16;
			
			// aapt resource value: 3
			public const int WeekView_maxHourHeight = 3;
			
			// aapt resource value: 2
			public const int WeekView_minHourHeight = 2;
			
			// aapt resource value: 10
			public const int WeekView_noOfVisibleDays = 10;
			
			// aapt resource value: 32
			public const int WeekView_nowLineColor = 32;
			
			// aapt resource value: 33
			public const int WeekView_nowLineThickness = 33;
			
			// aapt resource value: 21
			public const int WeekView_overlappingEventGap = 21;
			
			// aapt resource value: 28
			public const int WeekView_pastBackgroundColor = 28;
			
			// aapt resource value: 30
			public const int WeekView_pastWeekendBackgroundColor = 30;
			
			// aapt resource value: 25
			public const int WeekView_showDistinctPastFutureColor = 25;
			
			// aapt resource value: 26
			public const int WeekView_showDistinctWeekendColor = 26;
			
			// aapt resource value: 31
			public const int WeekView_showNowLine = 31;
			
			// aapt resource value: 4
			public const int WeekView_textSize = 4;
			
			// aapt resource value: 14
			public const int WeekView_todayBackgroundColor = 14;
			
			// aapt resource value: 15
			public const int WeekView_todayHeaderTextColor = 15;
			
			// aapt resource value: 35
			public const int WeekView_verticalFlingEnabled = 35;
			
			// aapt resource value: 23
			public const int WeekView_xScrollingSpeed = 23;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
